language: haxe

haxe:
  - development
  - "3.2.0"
  - "3.1.3"

os:
  - linux
  - osx

sudo: false

script:
  - haxe haxelib.hxml
  - haxe legacyhaxelib.hxml
  - haxelib install hx2compat
  - mkdir -p www/legacy
  - haxe legacysite.hxml
  # - haxelib install newsite.hxml --always
  # - haxe newsite.hxml
  - ./test.sh
