language: haxe

env:
  global:
    # deploy_key_decrypt
    - secure: "cWYcbB7z97sW4yZtz9qcYrEhFZktNjQMOraPm7Vy0FsCMqb4r314Fk8rJze+yDbOKGdsIz6VNHE8nlsQN3EgGiVFJnF8xv6GAlfHPuaVomP2vO7W0A+l7xVy2/326MQJP8JoMgdebDi71yxKeEhYA+mVliI9qql9yfD2YOBmilQ="

matrix:
  include:
    # Linux
    - os: linux
      language: haxe
      haxe: development
      sudo: required
      services: [docker]
    - os: linux
      language: haxe
      haxe: 3.2.1
      sudo: required
      services: [docker]
      env:
        - DEPLOY=1
    - os: linux
      language: haxe
      haxe: 3.1.3
      sudo: false
    # Mac
    - os: osx
      language: haxe
      haxe: development
    - os: osx
      language: haxe
      haxe: 3.2.1
    - os: osx
      language: haxe
      haxe: 3.1.3

install:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update;
      brew cask install virtualbox &&
      brew install docker docker-compose docker-machine &&
      docker-machine create --driver virtualbox default &&
      eval "$(docker-machine env default)";
    fi

script:
  # run our CI script
  - haxe ci.hxml
  # Deploy to lib.haxe.org
  - if [ -n "$deploy_key_decrypt" ] && [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_BRANCH" = "master" ] && [ -n "$DEPLOY" ]; then
      openssl aes-256-cbc -k "$deploy_key_decrypt" -in deploy_key.enc -out deploy_key -d;
      chmod 600 deploy_key;
      eval `ssh-agent -s`;
      ssh-add deploy_key;
      scp haxelib@lib.haxe.org:/data/haxelib/www/.htaccess www/;
      scp haxelib@lib.haxe.org:/data/haxelib/www/dbconfig.json www/;
      git config --global user.name "TravisCI";
      git config --global user.email "travisci@haxe.org";
      haxelib run ufront deploy;
    fi

cache:
  directories:
    - deploy

addons:
  ssh_known_hosts: lib.haxe.org