version: "{build}"

services:
  - mysql

install:
  - npm -g install bower
  - cinst haxe -y
  - cinst nssm -y
  - RefreshEnv
  - haxelib setup haxelib_repo
  - haxelib install all --always
  - haxelib git aws-sdk-neko https://github.com/andyli/aws-sdk-neko.git
  - haxelib install tora
  - haxelib list

build: off

test_script:
  - haxe ci.hxml
