version: "{build}"

install:
    - cinst haxe -y

build_script:
    - haxe haxelib.hxml
    - haxe legacyhaxelib.hxml
    - haxe legacysite.hxml
    - haxe test.hxml

test_script:
    - neko bin/test.n
